[PHP]
extension_dir = "ext"
extension=curl
extension=mbstring
extension=openssl
extension=pdo_mysql
extension=pdo_sqlite
extension=sqlite3
extension=zip

memory_limit = 256M
post_max_size = 64M
upload_max_filesize = 64M
date.timezone = "America/Bahia"

display_errors = Off
log_errors = On
error_log = "../../logs/php_error.log"
